#端口号
server:
  port: ${port:9091}
#数据源
spring:
  #应用名称
  application:
      name: user-service
  #数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud
    username: root
    password: root
#mybatis配置
mybatis:
  type-aliases-package: com.itheima.domain
  mapper-locations: classpath:com/itheima/mapper/**/*.xml
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
#Eureka
eureka:
  #Eureka客户端配置
  client:
    #Eureka服务地址
    service-url:
      #单个Eureka服务配置
      defaultZone: http://127.0.0.1:9092/eureka
      #Eureka高可用集群配置
      #defaultZone: http://127.0.0.1:9092/eureka,http://127.0.0.1:9093/eureka
  #Eureka实例配置
  instance:
    #更倾向于使用IP地址,而不是hostname
    prefer-ip-address: true
    #IP地址
    ip-address: 127.0.0.1
    #服务续约(renew)的间隔,默认为30秒
    lease-renewal-interval-in-seconds: 5
    #服务失效时间,默认值90秒
    lease-expiration-duration-in-seconds: 5
